# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: codegraph.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'codegraph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63odegraph.proto\x12\tcodegraph\"D\n\x0cParseRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\"V\n\rParseResponse\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\"\n\x07symbols\x18\x02 \x03(\x0b\x32\x11.codegraph.Symbol\x12\x0e\n\x06\x65rrors\x18\x03 \x03(\t\"\x96\x01\n\x06Symbol\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0equalified_name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x12\n\nstart_line\x18\x04 \x01(\x05\x12\x10\n\x08\x65nd_line\x18\x05 \x01(\x05\x12\x0c\n\x04hash\x18\x06 \x01(\t\x12\r\n\x05\x63\x61lls\x18\x07 \x03(\t\x12\x15\n\rinherits_from\x18\x08 \x03(\t\"M\n\x0cIndexRequest\x12\x11\n\troot_path\x18\x01 \x01(\t\x12\x11\n\trecursive\x18\x02 \x01(\x08\x12\x17\n\x0fignore_patterns\x18\x03 \x03(\t\"z\n\rIndexProgress\x12\x14\n\x0c\x63urrent_file\x18\x01 \x01(\t\x12\x17\n\x0f\x66iles_processed\x18\x02 \x01(\x05\x12\x13\n\x0btotal_files\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t\"<\n\x0cSliceRequest\x12\x19\n\x11target_symbol_uri\x18\x01 \x01(\t\x12\x11\n\tmax_depth\x18\x02 \x01(\x05\"e\n\rSliceResponse\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\t\x12\x15\n\roriginal_size\x18\x02 \x01(\x03\x12\x13\n\x0bpruned_size\x18\x03 \x01(\x03\x12\x17\n\x0fsavings_percent\x18\x04 \x01(\x01\x32\xdb\x01\n\x10\x43odeGraphService\x12>\n\tParseFile\x12\x17.codegraph.ParseRequest\x1a\x18.codegraph.ParseResponse\x12\x46\n\x0fIndexRepository\x12\x17.codegraph.IndexRequest\x1a\x18.codegraph.IndexProgress0\x01\x12?\n\nSliceGraph\x12\x17.codegraph.SliceRequest\x1a\x18.codegraph.SliceResponseBJ\n\x13\x63om.swarm.codegraphB\x0e\x43odeGraphProtoP\x01Z!github.com/swarm/codegraph/gen/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'codegraph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.swarm.codegraphB\016CodeGraphProtoP\001Z!github.com/swarm/codegraph/gen/go'
  _globals['_PARSEREQUEST']._serialized_start=30
  _globals['_PARSEREQUEST']._serialized_end=98
  _globals['_PARSERESPONSE']._serialized_start=100
  _globals['_PARSERESPONSE']._serialized_end=186
  _globals['_SYMBOL']._serialized_start=189
  _globals['_SYMBOL']._serialized_end=339
  _globals['_INDEXREQUEST']._serialized_start=341
  _globals['_INDEXREQUEST']._serialized_end=418
  _globals['_INDEXPROGRESS']._serialized_start=420
  _globals['_INDEXPROGRESS']._serialized_end=542
  _globals['_SLICEREQUEST']._serialized_start=544
  _globals['_SLICEREQUEST']._serialized_end=604
  _globals['_SLICERESPONSE']._serialized_start=606
  _globals['_SLICERESPONSE']._serialized_end=707
  _globals['_CODEGRAPHSERVICE']._serialized_start=710
  _globals['_CODEGRAPHSERVICE']._serialized_end=929
# @@protoc_insertion_point(module_scope)
