# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import codegraph_pb2 as codegraph__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in codegraph_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CodeGraphServiceStub(object):
    """The CodeGraph service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseFile = channel.unary_unary(
                '/codegraph.CodeGraphService/ParseFile',
                request_serializer=codegraph__pb2.ParseRequest.SerializeToString,
                response_deserializer=codegraph__pb2.ParseResponse.FromString,
                _registered_method=True)
        self.IndexRepository = channel.unary_stream(
                '/codegraph.CodeGraphService/IndexRepository',
                request_serializer=codegraph__pb2.IndexRequest.SerializeToString,
                response_deserializer=codegraph__pb2.IndexProgress.FromString,
                _registered_method=True)
        self.SliceGraph = channel.unary_unary(
                '/codegraph.CodeGraphService/SliceGraph',
                request_serializer=codegraph__pb2.SliceRequest.SerializeToString,
                response_deserializer=codegraph__pb2.SliceResponse.FromString,
                _registered_method=True)


class CodeGraphServiceServicer(object):
    """The CodeGraph service definition.
    """

    def ParseFile(self, request, context):
        """Parses a single file and returns its structure (symbols, calls).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexRepository(self, request, context):
        """Indexes a repository or directory, streaming progress updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SliceGraph(self, request, context):
        """Generates a "Skeleton View" of the code graph centered on a symbol.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeGraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseFile,
                    request_deserializer=codegraph__pb2.ParseRequest.FromString,
                    response_serializer=codegraph__pb2.ParseResponse.SerializeToString,
            ),
            'IndexRepository': grpc.unary_stream_rpc_method_handler(
                    servicer.IndexRepository,
                    request_deserializer=codegraph__pb2.IndexRequest.FromString,
                    response_serializer=codegraph__pb2.IndexProgress.SerializeToString,
            ),
            'SliceGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.SliceGraph,
                    request_deserializer=codegraph__pb2.SliceRequest.FromString,
                    response_serializer=codegraph__pb2.SliceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'codegraph.CodeGraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('codegraph.CodeGraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CodeGraphService(object):
    """The CodeGraph service definition.
    """

    @staticmethod
    def ParseFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codegraph.CodeGraphService/ParseFile',
            codegraph__pb2.ParseRequest.SerializeToString,
            codegraph__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndexRepository(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/codegraph.CodeGraphService/IndexRepository',
            codegraph__pb2.IndexRequest.SerializeToString,
            codegraph__pb2.IndexProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SliceGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codegraph.CodeGraphService/SliceGraph',
            codegraph__pb2.SliceRequest.SerializeToString,
            codegraph__pb2.SliceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
