# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestration_engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orchestration_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aorchestration_engine.proto\x12\x0corchestrator\"=\n\x0e\x43lusterRequest\x12+\n\x08\x66\x61ilures\x18\x01 \x03(\x0b\x32\x19.orchestrator.FailureInfo\"I\n\x0b\x46\x61ilureInfo\x12\x0f\n\x07\x65xec_id\x18\x01 \x01(\t\x12\x0c\n\x04note\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\r\n\x05stack\x18\x04 \x01(\t\"(\n\x0f\x43lusterResponse\x12\x15\n\rjson_clusters\x18\x01 \x01(\t\"G\n\x0bRuleRequest\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0c\n\x04note\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x12\r\n\x05stack\x18\x04 \x01(\t\"\x1c\n\x0cRuleResponse\x12\x0c\n\x04rule\x18\x01 \x01(\t\",\n\x10RouteTaskRequest\x12\x18\n\x10task_description\x18\x01 \x01(\t\"\'\n\x11RouteTaskResponse\x12\x12\n\nagent_type\x18\x01 \x01(\t\":\n\x11StateGraphRequest\x12\x15\n\rcurrent_state\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\"(\n\x12StateGraphResponse\x12\x12\n\nnext_state\x18\x01 \x01(\t\"\x8a\x01\n\x14LlmCompletionRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x15\n\rsystem_prompt\x18\x03 \x01(\t\x12\x11\n\tjson_mode\x18\x04 \x01(\x08\x12\x12\n\ntools_json\x18\x05 \x01(\t\x12\x15\n\rmessages_json\x18\x06 \x01(\t\"+\n\x15LlmCompletionResponse\x12\x12\n\ncompletion\x18\x01 \x01(\t2\xae\x01\n\x0e\x41nalystService\x12N\n\x0f\x43lusterFailures\x12\x1c.orchestrator.ClusterRequest\x1a\x1d.orchestrator.ClusterResponse\x12L\n\x13GenerateGoldenRules\x12\x19.orchestrator.RuleRequest\x1a\x1a.orchestrator.RuleResponse2\xba\x01\n\x13OrchestratorService\x12L\n\tRouteTask\x12\x1e.orchestrator.RouteTaskRequest\x1a\x1f.orchestrator.RouteTaskResponse\x12U\n\x10ManageStateGraph\x12\x1f.orchestrator.StateGraphRequest\x1a .orchestrator.StateGraphResponse2h\n\x11LlmGatewayService\x12S\n\x08\x43omplete\x12\".orchestrator.LlmCompletionRequest\x1a#.orchestrator.LlmCompletionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestration_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLUSTERREQUEST']._serialized_start=44
  _globals['_CLUSTERREQUEST']._serialized_end=105
  _globals['_FAILUREINFO']._serialized_start=107
  _globals['_FAILUREINFO']._serialized_end=180
  _globals['_CLUSTERRESPONSE']._serialized_start=182
  _globals['_CLUSTERRESPONSE']._serialized_end=222
  _globals['_RULEREQUEST']._serialized_start=224
  _globals['_RULEREQUEST']._serialized_end=295
  _globals['_RULERESPONSE']._serialized_start=297
  _globals['_RULERESPONSE']._serialized_end=325
  _globals['_ROUTETASKREQUEST']._serialized_start=327
  _globals['_ROUTETASKREQUEST']._serialized_end=371
  _globals['_ROUTETASKRESPONSE']._serialized_start=373
  _globals['_ROUTETASKRESPONSE']._serialized_end=412
  _globals['_STATEGRAPHREQUEST']._serialized_start=414
  _globals['_STATEGRAPHREQUEST']._serialized_end=472
  _globals['_STATEGRAPHRESPONSE']._serialized_start=474
  _globals['_STATEGRAPHRESPONSE']._serialized_end=514
  _globals['_LLMCOMPLETIONREQUEST']._serialized_start=517
  _globals['_LLMCOMPLETIONREQUEST']._serialized_end=655
  _globals['_LLMCOMPLETIONRESPONSE']._serialized_start=657
  _globals['_LLMCOMPLETIONRESPONSE']._serialized_end=700
  _globals['_ANALYSTSERVICE']._serialized_start=703
  _globals['_ANALYSTSERVICE']._serialized_end=877
  _globals['_ORCHESTRATORSERVICE']._serialized_start=880
  _globals['_ORCHESTRATORSERVICE']._serialized_end=1066
  _globals['_LLMGATEWAYSERVICE']._serialized_start=1068
  _globals['_LLMGATEWAYSERVICE']._serialized_end=1172
# @@protoc_insertion_point(module_scope)
