# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import orchestration_engine_pb2 as orchestration__engine__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orchestration_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalystServiceStub(object):
    """--- Analyst Service ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClusterFailures = channel.unary_unary(
                '/orchestrator.AnalystService/ClusterFailures',
                request_serializer=orchestration__engine__pb2.ClusterRequest.SerializeToString,
                response_deserializer=orchestration__engine__pb2.ClusterResponse.FromString,
                _registered_method=True)
        self.GenerateGoldenRules = channel.unary_unary(
                '/orchestrator.AnalystService/GenerateGoldenRules',
                request_serializer=orchestration__engine__pb2.RuleRequest.SerializeToString,
                response_deserializer=orchestration__engine__pb2.RuleResponse.FromString,
                _registered_method=True)


class AnalystServiceServicer(object):
    """--- Analyst Service ---
    """

    def ClusterFailures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateGoldenRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalystServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClusterFailures': grpc.unary_unary_rpc_method_handler(
                    servicer.ClusterFailures,
                    request_deserializer=orchestration__engine__pb2.ClusterRequest.FromString,
                    response_serializer=orchestration__engine__pb2.ClusterResponse.SerializeToString,
            ),
            'GenerateGoldenRules': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateGoldenRules,
                    request_deserializer=orchestration__engine__pb2.RuleRequest.FromString,
                    response_serializer=orchestration__engine__pb2.RuleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.AnalystService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestrator.AnalystService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalystService(object):
    """--- Analyst Service ---
    """

    @staticmethod
    def ClusterFailures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.AnalystService/ClusterFailures',
            orchestration__engine__pb2.ClusterRequest.SerializeToString,
            orchestration__engine__pb2.ClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateGoldenRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.AnalystService/GenerateGoldenRules',
            orchestration__engine__pb2.RuleRequest.SerializeToString,
            orchestration__engine__pb2.RuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OrchestratorServiceStub(object):
    """--- Orchestrator Core ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteTask = channel.unary_unary(
                '/orchestrator.OrchestratorService/RouteTask',
                request_serializer=orchestration__engine__pb2.RouteTaskRequest.SerializeToString,
                response_deserializer=orchestration__engine__pb2.RouteTaskResponse.FromString,
                _registered_method=True)
        self.ManageStateGraph = channel.unary_unary(
                '/orchestrator.OrchestratorService/ManageStateGraph',
                request_serializer=orchestration__engine__pb2.StateGraphRequest.SerializeToString,
                response_deserializer=orchestration__engine__pb2.StateGraphResponse.FromString,
                _registered_method=True)


class OrchestratorServiceServicer(object):
    """--- Orchestrator Core ---
    """

    def RouteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ManageStateGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteTask,
                    request_deserializer=orchestration__engine__pb2.RouteTaskRequest.FromString,
                    response_serializer=orchestration__engine__pb2.RouteTaskResponse.SerializeToString,
            ),
            'ManageStateGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.ManageStateGraph,
                    request_deserializer=orchestration__engine__pb2.StateGraphRequest.FromString,
                    response_serializer=orchestration__engine__pb2.StateGraphResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.OrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestrator.OrchestratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorService(object):
    """--- Orchestrator Core ---
    """

    @staticmethod
    def RouteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.OrchestratorService/RouteTask',
            orchestration__engine__pb2.RouteTaskRequest.SerializeToString,
            orchestration__engine__pb2.RouteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ManageStateGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.OrchestratorService/ManageStateGraph',
            orchestration__engine__pb2.StateGraphRequest.SerializeToString,
            orchestration__engine__pb2.StateGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LlmGatewayServiceStub(object):
    """--- LLM Gateway ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Complete = channel.unary_unary(
                '/orchestrator.LlmGatewayService/Complete',
                request_serializer=orchestration__engine__pb2.LlmCompletionRequest.SerializeToString,
                response_deserializer=orchestration__engine__pb2.LlmCompletionResponse.FromString,
                _registered_method=True)


class LlmGatewayServiceServicer(object):
    """--- LLM Gateway ---
    """

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=orchestration__engine__pb2.LlmCompletionRequest.FromString,
                    response_serializer=orchestration__engine__pb2.LlmCompletionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.LlmGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestrator.LlmGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LlmGatewayService(object):
    """--- LLM Gateway ---
    """

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.LlmGatewayService/Complete',
            orchestration__engine__pb2.LlmCompletionRequest.SerializeToString,
            orchestration__engine__pb2.LlmCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
