# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import orchestrator_pb2 as orchestrator__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orchestrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteTask = channel.unary_unary(
                '/orchestrator.v1.OrchestratorService/RouteTask',
                request_serializer=orchestrator__pb2.RouteTaskRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.RouteTaskResponse.FromString,
                _registered_method=True)
        self.ManageStateGraph = channel.unary_unary(
                '/orchestrator.v1.OrchestratorService/ManageStateGraph',
                request_serializer=orchestrator__pb2.StateGraphRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.StateGraphResponse.FromString,
                _registered_method=True)


class OrchestratorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RouteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ManageStateGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteTask,
                    request_deserializer=orchestrator__pb2.RouteTaskRequest.FromString,
                    response_serializer=orchestrator__pb2.RouteTaskResponse.SerializeToString,
            ),
            'ManageStateGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.ManageStateGraph,
                    request_deserializer=orchestrator__pb2.StateGraphRequest.FromString,
                    response_serializer=orchestrator__pb2.StateGraphResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.v1.OrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestrator.v1.OrchestratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RouteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.v1.OrchestratorService/RouteTask',
            orchestrator__pb2.RouteTaskRequest.SerializeToString,
            orchestrator__pb2.RouteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ManageStateGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.v1.OrchestratorService/ManageStateGraph',
            orchestrator__pb2.StateGraphRequest.SerializeToString,
            orchestrator__pb2.StateGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AnalystServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OptimizePrompt = channel.unary_unary(
                '/orchestrator.v1.AnalystService/OptimizePrompt',
                request_serializer=orchestrator__pb2.OptimizePromptRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.OptimizePromptResponse.FromString,
                _registered_method=True)
        self.ClusterFailures = channel.unary_unary(
                '/orchestrator.v1.AnalystService/ClusterFailures',
                request_serializer=orchestrator__pb2.ClusterFailuresRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.ClusterFailuresResponse.FromString,
                _registered_method=True)


class AnalystServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OptimizePrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClusterFailures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalystServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OptimizePrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimizePrompt,
                    request_deserializer=orchestrator__pb2.OptimizePromptRequest.FromString,
                    response_serializer=orchestrator__pb2.OptimizePromptResponse.SerializeToString,
            ),
            'ClusterFailures': grpc.unary_unary_rpc_method_handler(
                    servicer.ClusterFailures,
                    request_deserializer=orchestrator__pb2.ClusterFailuresRequest.FromString,
                    response_serializer=orchestrator__pb2.ClusterFailuresResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.v1.AnalystService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestrator.v1.AnalystService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalystService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OptimizePrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.v1.AnalystService/OptimizePrompt',
            orchestrator__pb2.OptimizePromptRequest.SerializeToString,
            orchestrator__pb2.OptimizePromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClusterFailures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.v1.AnalystService/ClusterFailures',
            orchestrator__pb2.ClusterFailuresRequest.SerializeToString,
            orchestrator__pb2.ClusterFailuresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LlmGatewayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Complete = channel.unary_unary(
                '/orchestrator.v1.LlmGatewayService/Complete',
                request_serializer=orchestrator__pb2.LlmCompletionRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.LlmCompletionResponse.FromString,
                _registered_method=True)


class LlmGatewayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=orchestrator__pb2.LlmCompletionRequest.FromString,
                    response_serializer=orchestrator__pb2.LlmCompletionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.v1.LlmGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestrator.v1.LlmGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LlmGatewayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.v1.LlmGatewayService/Complete',
            orchestrator__pb2.LlmCompletionRequest.SerializeToString,
            orchestrator__pb2.LlmCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
