# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestrator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12orchestrator.proto\x12\x0forchestrator.v1\",\n\x10RouteTaskRequest\x12\x18\n\x10task_description\x18\x01 \x01(\t\"\'\n\x11RouteTaskResponse\x12\x12\n\nagent_type\x18\x01 \x01(\t\":\n\x11StateGraphRequest\x12\x15\n\rcurrent_state\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\"(\n\x12StateGraphResponse\x12\x12\n\nnext_state\x18\x01 \x01(\t\"\'\n\x15OptimizePromptRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"2\n\x16OptimizePromptResponse\x12\x18\n\x10optimized_prompt\x18\x01 \x01(\t\"*\n\x16\x43lusterFailuresRequest\x12\x10\n\x08\x66\x61ilures\x18\x01 \x03(\t\"+\n\x17\x43lusterFailuresResponse\x12\x10\n\x08\x63lusters\x18\x01 \x03(\t\"\x8a\x01\n\x14LlmCompletionRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x15\n\rsystem_prompt\x18\x03 \x01(\t\x12\x11\n\tjson_mode\x18\x04 \x01(\x08\x12\x12\n\ntools_json\x18\x05 \x01(\t\x12\x15\n\rmessages_json\x18\x06 \x01(\t\"+\n\x15LlmCompletionResponse\x12\x12\n\ncompletion\x18\x01 \x01(\t2\xc6\x01\n\x13OrchestratorService\x12R\n\tRouteTask\x12!.orchestrator.v1.RouteTaskRequest\x1a\".orchestrator.v1.RouteTaskResponse\x12[\n\x10ManageStateGraph\x12\".orchestrator.v1.StateGraphRequest\x1a#.orchestrator.v1.StateGraphResponse2\xd9\x01\n\x0e\x41nalystService\x12\x61\n\x0eOptimizePrompt\x12&.orchestrator.v1.OptimizePromptRequest\x1a\'.orchestrator.v1.OptimizePromptResponse\x12\x64\n\x0f\x43lusterFailures\x12\'.orchestrator.v1.ClusterFailuresRequest\x1a(.orchestrator.v1.ClusterFailuresResponse2n\n\x11LlmGatewayService\x12Y\n\x08\x43omplete\x12%.orchestrator.v1.LlmCompletionRequest\x1a&.orchestrator.v1.LlmCompletionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTETASKREQUEST']._serialized_start=39
  _globals['_ROUTETASKREQUEST']._serialized_end=83
  _globals['_ROUTETASKRESPONSE']._serialized_start=85
  _globals['_ROUTETASKRESPONSE']._serialized_end=124
  _globals['_STATEGRAPHREQUEST']._serialized_start=126
  _globals['_STATEGRAPHREQUEST']._serialized_end=184
  _globals['_STATEGRAPHRESPONSE']._serialized_start=186
  _globals['_STATEGRAPHRESPONSE']._serialized_end=226
  _globals['_OPTIMIZEPROMPTREQUEST']._serialized_start=228
  _globals['_OPTIMIZEPROMPTREQUEST']._serialized_end=267
  _globals['_OPTIMIZEPROMPTRESPONSE']._serialized_start=269
  _globals['_OPTIMIZEPROMPTRESPONSE']._serialized_end=319
  _globals['_CLUSTERFAILURESREQUEST']._serialized_start=321
  _globals['_CLUSTERFAILURESREQUEST']._serialized_end=363
  _globals['_CLUSTERFAILURESRESPONSE']._serialized_start=365
  _globals['_CLUSTERFAILURESRESPONSE']._serialized_end=408
  _globals['_LLMCOMPLETIONREQUEST']._serialized_start=411
  _globals['_LLMCOMPLETIONREQUEST']._serialized_end=549
  _globals['_LLMCOMPLETIONRESPONSE']._serialized_start=551
  _globals['_LLMCOMPLETIONRESPONSE']._serialized_end=594
  _globals['_ORCHESTRATORSERVICE']._serialized_start=597
  _globals['_ORCHESTRATORSERVICE']._serialized_end=795
  _globals['_ANALYSTSERVICE']._serialized_start=798
  _globals['_ANALYSTSERVICE']._serialized_end=1015
  _globals['_LLMGATEWAYSERVICE']._serialized_start=1017
  _globals['_LLMGATEWAYSERVICE']._serialized_end=1127
# @@protoc_insertion_point(module_scope)
