#!/usr/bin/env python3
"""
Synapse Swarm Onboarding Wizard.
Inspired by Openclaw's onboarding experience.
"""
import os
import sys
import subprocess
import getpass
import time

ASCII_ART = r"""
   _____
  / ____|
 | (___  _   _ _ __   __ _ _ __  ___  ___
  \___ \| | | | '_ \ / _` | '_ \/ __|/ _ \
  ____) | |_| | | | | (_| | |_) \__ \  __/
 |_____/ \__, |_| |_|\__,_| .__/|___/\___|
          __/ |           | |
         |___/            |_|

      >>> SWARM ONBOARDING WIZARD <<<
"""

ENV_FILE = ".env"

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def print_header():
    clear_screen()
    print(ASCII_ART)
    print("Welcome to the Synapse Swarm setup wizard.")
    print("This tool will configure your environment variables and get you started.\n")
    print("⚠️  WARNING: This system has autonomous capabilities.")
    print("    It can execute code, read files, and access the internet.")
    print("    Use with caution and monitor its actions.\n")

def load_env():
    """Load environment variables from .env file into os.environ."""
    if not os.path.exists(ENV_FILE):
        return

    with open(ENV_FILE, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            try:
                key, value = line.split("=", 1)
                # Remove quotes if present
                if (value.startswith('"') and value.endswith('"')) or \
                   (value.startswith("'") and value.endswith("'")):
                    value = value[1:-1]
                os.environ[key] = value
            except ValueError:
                continue

def save_env(config):
    """Save configuration to .env file."""
    print(f"\n💾 Saving configuration to {ENV_FILE}...")

    # Read existing lines to preserve comments if possible, but for now simple append/overwrite
    existing = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE, "r") as f:
            for line in f:
                if "=" in line and not line.startswith("#"):
                    try:
                        k, v = line.strip().split("=", 1)
                        existing[k] = v
                    except ValueError:
                        continue

    # Merge
    for k, v in config.items():
        existing[k] = v

    with open(ENV_FILE, "w") as f:
        f.write("# Synapse Swarm Configuration\n")
        f.write(f"# Generated by Onboarding Wizard on {time.ctime()}\n\n")
        for k, v in existing.items():
            f.write(f"{k}={v}\n")

    print("✅ Configuration saved.")

def ask(question, default=None, secret=False):
    """Ask a question with optional default value."""
    prompt = f"{question}"
    if default:
        prompt += f" [{default}]"
    prompt += ": "

    if secret:
        response = getpass.getpass(prompt)
    else:
        response = input(prompt)

    return response.strip() or default

def run_wizard():
    print_header()

    if os.path.exists(ENV_FILE):
        overwrite = ask(f"Found existing {ENV_FILE}. Overwrite?", default="no").lower()
        if overwrite not in ["y", "yes"]:
            print("Skipping configuration updates.")
            return

    config = {}

    print("\n--- 🧠 LLM Configuration ---")
    print("We need an LLM provider to power the agents.")
    config["OPENAI_API_KEY"] = ask("Enter your OpenAI API Key", secret=True)
    config["LLM_MODEL"] = ask("Enter LLM Model to use", default="gpt-4o")
    config["MAX_DAILY_BUDGET"] = ask("Max Daily Budget ($)", default="10.0")

    print("\n--- 🕸️  Synapse Configuration ---")
    config["SYNAPSE_GRPC_HOST"] = ask("Synapse Host", default="localhost")
    config["SYNAPSE_GRPC_PORT"] = ask("Synapse Port", default="50051")
    # Using relative path is safer for docker/portability
    config["GRAPH_STORAGE_PATH"] = ask("Graph Data Path", default="./synapse-data")

    print("\n--- 🛠️  Optional Integrations ---")
    setup_trello = ask("Configure Trello Bridge? (Required for PM Agent)", default="no").lower()
    if setup_trello in ["y", "yes"]:
        config["TRELLO_API_KEY"] = ask("Trello API Key", secret=True)
        config["TRELLO_TOKEN"] = ask("Trello Token", secret=True)
        config["TRELLO_BOARD_ID"] = ask("Trello Board ID")

    setup_telegram = ask("Configure Telegram Alerts? (For Budget Warnings)", default="no").lower()
    if setup_telegram in ["y", "yes"]:
        config["TELEGRAM_BOT_TOKEN"] = ask("Telegram Bot Token", secret=True)
        config["TELEGRAM_CHAT_ID"] = ask("Telegram Chat ID")

    # Save
    save_env(config)

    # Reload env vars immediately for this process
    load_env()

    print("\n--- 🚀 Setup & Launch ---")

    # Check if Synapse is built
    if not os.path.exists("./synapse"):
        build = ask("Synapse binary not found. Build it now? (Takes ~2 mins)", default="yes").lower()
        if build in ["y", "yes"]:
            print("🔨 Running setup_synapse.sh...")
            subprocess.run(["bash", "scripts/setup_synapse.sh"], check=False)

    start = ask("Start all services now? (Synapse + FastEmbed)", default="yes").lower()
    if start in ["y", "yes"]:
        print("🚀 Starting services...")
        # Detach process properly
        with open("bridge_output.log", "a") as out, open("bridge_output.log", "a") as err:
            subprocess.Popen(["bash", "scripts/start_all.sh"],
                             stdout=out,
                             stderr=err,
                             stdin=subprocess.DEVNULL,
                             start_new_session=True)
        print("Services started in background. Check bridge_output.log for details.")
        time.sleep(2) # Give it a moment

    print("\n✅ Onboarding Complete!")
    print("Run 'python3 scripts/kilo_interactive.py' to enter the Command Center.")
    # input("Press Enter to continue...") # Removed to avoid hang if run via automation

def check_or_run():
    """Check if critical config exists, otherwise run wizard."""
    # Try loading first
    load_env()

    if not os.getenv("OPENAI_API_KEY"):
        print("⚠️  Configuration missing (OPENAI_API_KEY).")
        # In automated environments (like CI), we can't ask interactively.
        # But for 'kilo_interactive', we assume a user.
        if sys.stdin.isatty():
            run = ask("Run onboarding wizard?", default="yes").lower()
            if run in ["y", "yes"]:
                run_wizard()
                return # Wizard reloads env
        else:
            print("Skipping interactive wizard (not a TTY).")
            # In CI, we expect ENV vars to be set via secrets, so just continue
            return

        # If user said no to wizard, check if they want to exit
        print("Continuing without wizard... (Some features may fail)")

if __name__ == "__main__":
    run_wizard()
